#!/bin/bash

if ! grep boarded /root/.bashrc > /dev/null 2>&1; then
    cat >> /root/.bashrc <<'EOF'
. /usr/share/bash-completion/bash_completion
export PATH=${PATH}:/tmp
export NPV_PROXY_TLS=true
export NPV_PROXY_TLS_CA_FILE=/etc/cluster-ca/ca.crt
export NPV_PROXY_TLS_SERVER_NAME=cilium-agent-proxy
. <(kubectl completion bash)
. <(npv completion bash)
# boarded
EOF
fi
