name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: The name of the tag to release (X.Y.Z)
permissions:
  contents: write
  packages: write
jobs:
  release:
    name: Release network-policy-viewer
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: main
          persist-credentials: true
      - name: Validate inputs
        env:
          VTAG: v${{ inputs.tag }}
        run: |
          if [[ ! "${VTAG}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag format. Please use X.Y.Z"
            exit 1
          fi
          if git rev-parse "${VTAG}" >/dev/null 2>&1; then
              echo "Tag ${VTAG} already exists"
              exit 1
          fi
      - name: Download Cilium CLI
        run: make download-cilium-cli
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push cilium-agent-proxy
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/cybozu-go/cilium-agent-proxy:${{ inputs.tag }}
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          cache: false
      - name: Build
        env:
          VTAG: v${{ inputs.tag }}
        run: |
          make build
          cd bin; tar -czvf "npv_${VTAG}_amd64.tar.gz" npv
      - name: Setup Git Config
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: Push tag
        env:
          VTAG: v${{ inputs.tag }}
        run: |
          git tag -a "${VTAG}" -m "Release network-policy-viewer ${VTAG}"
          git push origin "${VTAG}"
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VTAG: v${{ inputs.tag }}
        run: |
          gh release create "${VTAG}" --title "Release ${VTAG}" --generate-notes
          gh release upload "${VTAG}" "bin/npv_${VTAG}_amd64.tar.gz" --clobber
